#!/bin/sh
# =============================================================================
# Turn sites.conf into a Caddyfile.
#
# Caddy stays a ready-made tool -- ARCHITECTURE.md is explicit that a reverse
# proxy is not something this project writes, because one mistake in TLS exposes
# every domain. What was missing was any configuration for it: the installer
# installed the package and never told it what to serve, so a fresh machine came
# up with Caddy running and answering nothing.
#
# This writes that configuration from one table, and refuses rather than guesses:
#
#   an empty table            -> nothing is written, and it says so
#   a target that is missing  -> refused, with the line number
#   a php site with no fpm    -> refused
#   caddy rejects the result  -> the old file is put back
#
# Usage:  sh generate_caddyfile.sh [--sites FILE] [--out FILE] [--dry-run]
# Exit:   0 written, 1 refused, 2 nothing to do
# =============================================================================

set -u

HERE=$(cd "$(dirname "$0")" && pwd)
SITES="${HERE}/sites.conf"
OUT=/usr/local/etc/caddy/Caddyfile
DRY=0

while [ $# -gt 0 ]; do
    case "$1" in
        --sites) SITES="$2"; shift 2 ;;
        --out)   OUT="$2"; shift 2 ;;
        --dry-run) DRY=1; shift ;;
        -h|--help) sed -n '2,20p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) echo "unknown option: $1" >&2; exit 1 ;;
    esac
done

say() { printf '%s\n' "$*"; }
die() { printf 'REFUSED: %s\n' "$*" >&2; exit 1; }

[ -f "$SITES" ] || die "no site table at ${SITES}"

# --- read the table --------------------------------------------------------
COUNT=0
PHP=0
BODY=""
LINE=0

while IFS= read -r raw; do
    LINE=$((LINE + 1))
    line=$(printf '%s' "$raw" | sed 's/#.*//' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
    [ -n "$line" ] || continue

    domain=$(printf '%s' "$line" | awk '{print $1}')
    kind=$(printf '%s' "$line" | awk '{print $2}')
    target=$(printf '%s' "$line" | awk '{print $3}')

    [ -n "$kind" ] && [ -n "$target" ] || \
        die "${SITES}:${LINE}: needs three fields: domain kind target"

    case "$domain" in
        *.*) ;;
        *) die "${SITES}:${LINE}: '${domain}' does not look like a domain" ;;
    esac

    case "$kind" in
        static|php)
            case "$target" in
                /*) ;;
                *) die "${SITES}:${LINE}: ${kind} needs an absolute path, got '${target}'" ;;
            esac
            # A site pointing at a directory that is not there serves 404s and
            # looks like a DNS problem for an hour before anyone checks.
            [ -d "$target" ] || \
                die "${SITES}:${LINE}: ${target} does not exist. Restore it first, or
         correct the path -- Caddy would serve nothing and blame the request."
            ;;
        proxy)
            case "$target" in
                *:[0-9]*) ;;
                *) die "${SITES}:${LINE}: proxy needs host:port, got '${target}'" ;;
            esac
            ;;
        *) die "${SITES}:${LINE}: unknown kind '${kind}'. Use static, php or proxy." ;;
    esac

    case "$kind" in
        static)
            BODY="${BODY}
http://${domain} {
	root * ${target}
	encode gzip
	file_server
	log {
		output file /var/log/caddy/${domain}.log
	}
}
"
            ;;
        php)
            PHP=1
            BODY="${BODY}
http://${domain} {
	root * ${target}
	encode gzip
	# The socket is php-fpm's default on FreeBSD. It is a unix socket rather
	# than a TCP port so nothing else on the machine can reach the
	# interpreter, which matters on a host that also runs a tunnel.
	php_fastcgi unix//var/run/php-fpm.sock
	file_server
	log {
		output file /var/log/caddy/${domain}.log
	}
}
"
            ;;
        proxy)
            BODY="${BODY}
http://${domain} {
	encode gzip
	reverse_proxy ${target}
	log {
		output file /var/log/caddy/${domain}.log
	}
}
"
            ;;
    esac
    COUNT=$((COUNT + 1))
done < "$SITES"

if [ "$COUNT" -eq 0 ]; then
    say "No sites declared in ${SITES}."
    say "Nothing was written: an empty Caddyfile is a proxy that answers"
    say "every request with a blank page and no reason."
    exit 2
fi

if [ "$PHP" -eq 1 ] && [ "$DRY" -eq 0 ] && ! command -v php-fpm >/dev/null 2>&1; then
    die "a site is declared php and php-fpm is not installed.
         The installer adds it: sh install_hajime_os.sh"
fi

# --- write it --------------------------------------------------------------
HEADER="# Generated by hajime-web/generate_caddyfile.sh from sites.conf.
# Edited by hand, this file lasts until the next run. Change sites.conf.
#
# Automatic HTTPS is off because nothing reaches this machine from the internet
# except through the Cloudflare tunnel, so Caddy cannot answer an ACME
# challenge. TLS is Cloudflare's at the edge. See sites.conf for the whole
# reasoning; it changes the day this host is exposed directly.

{
	auto_https off
	admin off
}
"

if [ "$DRY" -eq 1 ]; then
    say "would write ${OUT} with ${COUNT} site(s):"
    printf '%s%s\n' "$HEADER" "$BODY"
    exit 0
fi

# Only when it is missing. `install -d -m 755` on a directory that already
# exists silently re-permissions it, and CI writes its test Caddyfile to /tmp:
# that one call took /tmp from 1777 down to 755, after which postgres could not
# create its socket lock file and the whole job failed three steps later with a
# message that named neither /tmp nor this script.
OUTDIR=$(dirname "$OUT")
[ -d "$OUTDIR" ] || install -d -m 755 "$OUTDIR" || die "cannot create ${OUTDIR}"
install -d -o www -g www -m 755 /var/log/caddy 2>/dev/null || true

TMP="${OUT}.hajime.$$"
printf '%s%s' "$HEADER" "$BODY" > "$TMP" || die "cannot write ${TMP}"

# Let Caddy be the judge. A config this script is happy with and Caddy is not
# leaves the proxy down after the next restart, which is the worst moment to
# find out.
if command -v caddy >/dev/null 2>&1; then
    if ! caddy validate --config "$TMP" --adapter caddyfile >/dev/null 2>&1; then
        caddy validate --config "$TMP" --adapter caddyfile 2>&1 | head -20 >&2
        rm -f "$TMP"
        die "caddy rejected the generated config; ${OUT} was left as it was"
    fi
fi

[ -f "$OUT" ] && [ ! -f "${OUT}.hajime-orig" ] && cp -p "$OUT" "${OUT}.hajime-orig"
mv "$TMP" "$OUT" || die "cannot replace ${OUT}"

say "${OUT}: ${COUNT} site(s)"
[ "$PHP" -eq 1 ] && say "one or more sites go through php-fpm"
say ""
say "Caddy reloads without dropping a connection:"
say "  service caddy reload"
exit 0
